### ISSUE TITLE
 Error while updating property 'strokeWidth' in shadow node of type: RNSVGLine

### ISSUE THREAD

**Issue by habeebrahmanpt** [indiespirit/react-native-chart-kit#14]
E/unknown:ReactNative: Exception in native call
    com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'strokeWidth' in shadow node of type: RNSVGLine
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:113)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
        at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:378)
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:289)
        at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:366)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
        at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:168)
        at com.facebook.react.uimanager.ReactStylesDiffMap.getString(ReactStylesDiffMap.java:71)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$StringPropSetter.extractProperty(ViewManagersPropertyCache.java:243)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPro

**Comment by Eduardo-Wegner** [comment]
i solved this making a downgrade on react-native-svg, i uninstall the 6 and install the 5.5.1
npm uninstall react-native-svg --save
npm install react-native-svg@5.5.1 --save

**Comment by themakerman** [comment]
+1. @Eduardo-Wegner did not worked for me.

**Comment by Eduardo-Wegner** [comment]
@themakerman, what's showing for you now ? copy and paste your output to try help you!

**Comment by Hermanya** [comment]
Sorry for the late response, I upgraded all dependencies for this package, so now it should be compatible with everything latest.
