### ISSUE TITLE
App crashed in release

### ISSUE THREAD

**Issue by emp3ror** [indiespirit/react-native-chart-kit#344]
I used simple barchart, it is all ok when working on debug mode, after I make a release build for android and test in phone, it crashed

**Comment by Damhan** [comment]
Needs more info, simple barchart working for me in a production android application.

**Comment by emp3ror** [comment]
> Needs more info, simple barchart working for me in a production android application.

How can I get production errors? it simply crashes

**Comment by Damhan** [comment]
[Link](https://developer.android.com/topic/performance/vitals/crash)

Here is a link to some resources describing how to explore crashes in production Android.

**Comment by orickcarvalho** [comment]
@emp3ror if you're using proguard-rules, you need to insert this in your android/app/proguard-rules.pro:
**-keep public class com.horcrux.svg.** {*;}**

**Comment by fernando-pascoal** [comment]
@emp3ror  you checked quantity of data? Maybe you tried render many data and device crash.

**Comment by quyetthang122** [comment]
I am having a same issue, when I am using a basic line chart. The app crashed when navigate to the screen with line chart.

**Comment by MrGVSV** [comment]
Having the same issue, except mine crashes in Dev Mode. Only Android and only if the LineChart is being rendered to the screen.

Android Studio spits out this error: 
<details>
<summary><code>java.lang.ArrayIndexOutOfBoundsException</code></summary>
<br>
<code>
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 13480
    java.lang.ArrayIndexOutOfBoundsException
        at android.graphics.DashPathEffect.<init>(DashPathEffect.java:36)
        at com.horcrux.svg.RenderableView.setupStrokePaint(RenderableView.java:466)
        at com.horcrux.svg.RenderableView.draw(RenderableView.java:380)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:339)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:104)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:339)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:104)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:339)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:104)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:339)
        at com.horcrux.svg.SvgView.drawChildren(SvgView.java:304)
        at com.horcrux.svg.SvgView.drawOutput(SvgView.java:255)
        at com.horcrux.svg.SvgView.onDraw(SvgView.java:106)
        at android.view.View.draw(View.java:20370)
        at android.view.View.updateDisplayListIfDirty(View.java:19315)
        at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:19306)
        at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:19306)
        at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:19306)
        at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.draw(View.java:20373)
        at android.widget.ScrollView.draw(ScrollView.java:2731)
        at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:465)
        at android.view.View.updateDisplayListIfDirty(View.java:19315)
        at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:20373)
        at android.view.View.updateDisplayListIfDirty(View.java:19315)
        at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:19306)
        at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:19306)
        at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.updateDisplayListIfDirty(View.java:19306)
        at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.updateDisplayListIfDirty(View.java:19306)
E/AndroidRuntime:     at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.updateDisplayListIfDirty(View.java:19306)
        at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:19306)
        at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:20373)
        at android.view.View.updateDisplayListIfDirty(View.java:19315)
        at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:19306)
        at android.view.View.draw(View.java:20093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:19306)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19274)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19274)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19274)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19274)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19274)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19274)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3496)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3283)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2818)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7817)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
</code>
</details>

I'm not sure if this is an issue on react-native-svg or here though.

**Comment by quyetthang122** [comment]
@emp3ror You can add this line: `-keep public class com.horcrux.svg.** { *; }`  to android/app/proguard-rules.pro, it fixed to me.

**Comment by NoamPaz** [comment]
> @emp3ror You can add this line: `-keep public class com.horcrux.svg.** { *; }` to android/app/proguard-rules.pro, it fixed to me.

If you enabled ProGuard this rule should fix the issue!

**Comment by amanrathore10** [comment]
> @emp3ror if you're using proguard-rules, you need to insert this line in your android/app/proguard-rules.pro:
> **-keep public class com.horcrux.svg.**** {*;}

This worked for me . App was working in debug mode but crashed in prod build. Thanks @henrineken

**Comment by MortezaHeydari97** [comment]
I've the same problem and it resolved by this line :
`-keep public class com.horcrux.svg.** {*;}`

So thanks @henrineken

**Comment by ViniciusMargotti** [comment]
Also solved, thanks everyone.

**Comment by Risovas** [comment]
Had this issue today, the proguard-rules answer from @henrineken fixed if for me as well, is this even documented anywhere by now?

**Comment by DipeshMajithia123** [comment]
@henrineken Thank you soooo much. It worked for me too!!!!! :)

**Comment by fordaf4445** [comment]
@henrineken  Thank you, It work for react-native-chart-kit

**Comment by AlexDimitriadis** [comment]
I noticed the same issue on Windows in debug, when I opened of the drawer or navigated away from the screen that contains the chart it would freeze for a couple of seconds and cause a big spike in RAM usage. I later added I show/hide button to the chart View and realized that the issue arises when the chart component unmounts. You can see the effect every time the button is pressed:
![chartUnmount](https://github.com/indiespirit/react-native-chart-kit/assets/32848015/75e5390f-8170-4ec7-9c6a-b7473b2ec3cb)

I also noticed that the spike is much smaller when the chart has no data.
I ended up manually unmounting the component when the drawer opens which improved the situation slightly (it still freezes but at least it doesn't crash) but the issue still persists. I haven't tested in release yet. Is there any solution for Windows?
