### ISSUE TITLE
Errors with web platform

### ISSUE THREAD

**Issue by ricohumme** [indiespirit/react-native-chart-kit#596]
Hi,

I'm getting these errors with the web platform. The iOS platform seems to be working as expected
```
Uncaught Invariant Violation: `createAnimatedComponent` does not support stateless functional components; use a class component instead.
    at invariant (http://localhost:19006/static/js/bundle.js:55972:15)
    at Object.createAnimatedComponent (http://localhost:19006/static/js/bundle.js:177863:60)
    at Module../node_modules/react-native-chart-kit/dist/line-chart/LineChart.js (http://localhost:19006/static/js/bundle.js:159926:101)
    at __webpack_require__ (http://localhost:19006/static/js/bundle.js:790:30)
    at fn (http://localhost:19006/static/js/bundle.js:101:20)
    at Module../node_modules/react-native-chart-kit/dist/line-chart/index.js (http://localhost:19006/static/js/bundle.js:160598:68)
    at __webpack_require__ (http://localhost:19006/static/js/bundle.js:790:30)
    at fn (http://localhost:19006/static/js/bundle.js:101:20)
    at Module../node_modules/react-native-chart-kit/dist/index.js (http://localhost:19006/static/js/bundle.js:159756:69)
    at __webpack_require__ (http://localhost:19006/static/js/bundle.js:790:30)
    at fn (http://localhost:19006/static/js/bundle.js:101:20)
    ...
```

I'm using the following setup:
"expo": "~44.0.0",
"react": "17.0.1",
"react-dom": "17.0.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz", // equivalent to 0.63,
"react-native-chart-kit": "^6.12.0", // latest
"react-native-reanimated": "~2.3.1", // current 2.3.3, compatible with expo
"react-native-web": "0.17.1",

Can someone please point me in the right direction?

**Comment by ahmed4game** [comment]
@ricohumme Did you find any solution to make it work with web platform?

**Comment by ricohumme** [comment]
@ahmed4game no, I ended up using `victory-native` which I'm quite happy with :)

**Comment by ahmed4game** [comment]
> @ahmed4game no, I ended up using `victory-native` which I'm quite happy with :)

Just went through it's documentation quickly. Are you sure It has support for web also?

**Comment by ricohumme** [comment]
@ahmed4game I implemented it in web with my current project so yeah I'm pretty sure about that :)
